# Generated by Django 5.0.1 on 2024-03-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('skils1', models.CharField(max_length=300)),
                ('skils2', models.CharField(max_length=300)),
                ('skils3', models.CharField(max_length=300)),
                ('skils4', models.CharField(max_length=300)),
                ('skils5', models.CharField(max_length=300)),
                ('skils6', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='about/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profession', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='clients/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('courses', models.IntegerField()),
                ('img', models.ImageField(upload_to='courses/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Index_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index_carousel/')),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='instructors/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Popular_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('person_name', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('students', models.IntegerField()),
                ('img', models.ImageField(upload_to='pupular_courses/')),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
            ],
        ),
    ]
